# Generated by Django 2.1.11 on 2019-09-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text',
            new_name='userText',
        ),
    ]
